#!/bin/sh
if [ $(id -u) != "0" ]; then
    echo "Error: You must be root to run this script"
    exit 1
fi
echo "========================================================================="
echo "FREEBSD APACHE PHP SETUP"
echo "========================================================================="
export PACKAGESITE=http://mirrors.163.com/FreeBSD/ports/i386/packages-9-current/Latest/
for pkg in autoconf268 pcre libiconv libxml2 oniguruma gettext curl mcrypt freetype jpeg png kbproto libICE libSM libX11 xextproto printproto libXau libXdmcp libpthread-stubs libxcb libXext libXp libXt libXmu libXpm libXaw libmemcached mysql55-server memcached mongodb subversion;
do pkg_add -r $pkg;done
fetch http://7shell.googlecode.com/svn/freebsd/up.tar.gz
fetch http://7shell.googlecode.com/svn/freebsd/apr.tar.gz
tar zxvf up.tar.gz
tar zxvf apache.tar.gz
tar zxvf php.tar.gz
tar zxvf apr.tar.gz
mv apache /usr/local/
mv php /usr/local/
mv apr /usr/local/
mkdir -p /var/www
chown -R www:www /var/www
echo "<?php phpinfo();?>">/var/www/index.php
fetch http://7shell.googlecode.com/svn/loader.conf
mv loader.conf /boot/defaults/
kldload accf_http
mv apache2 /usr/local/etc/rc.d/apache
chmod +x /usr/local/etc/rc.d/apache
fetch http://7shell.googlecode.com/svn/my.cnf
mv my.cnf /var/db/mysql/
echo 'apache_enable="YES"'>>/etc/rc.conf
echo 'mysql_enable="YES"'>>/etc/rc.conf
echo 'memcached_enable="YES"'>>/etc/rc.conf
echo 'mongod_enable="YES"'>>/etc/rc.conf
pkill -9 httpd
pkill -9 mysqld
service apache start
service mysql-server start
service memcached start
service  mongod start
rm *.gz

